apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./components/victoria-metrics-crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system