apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: flux-operator
  wait: true
  path: ./components/flux-instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system